import os

EMAIL_LOGIN = os.getenv("TAMIZDAT_EMAIL_LOGIN")
EMAIL_PASSWORD = os.getenv("TAMIZDAT_EMAIL_PASSWORD")
EMAIL_HOST = os.getenv("TAMIZDAT_EMAIL_HOST")
EMAIL_PORT = os.getenv("TAMIZDAT_EMAIL_PORT")

TELEGRAM_TOKEN = os.getenv("TAMIZDAT_TELEGRAM_TOKEN")

