from os import getenv

EMAIL_LOGIN = getenv("TAMIZDAT_EMAIL_LOGIN")
EMAIL_PASSWORD = getenv("TAMIZDAT_EMAIL_PASSWORD")
EMAIL_HOST = getenv("TAMIZDAT_EMAIL_HOST")
EMAIL_PORT = getenv("TAMIZDAT_EMAIL_PORT")

TELEGRAM_TOKEN = getenv("TAMIZDAT_TELEGRAM_TOKEN")
